# Site settings
title: Santhosh Kumar
description: My Modern Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://santhoshms47.github.io/

# User settings
username: Santhosh Kumar
user_description: I'm a Student, Programmer, Developer and Designer. Always searching for the next challenge; No task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT. I'm one of the two guys behind all the JS related stuff.
user_title: Student | Programmer
email: santhoshkms47@gmail.com
twitter_username: santhosh47
github_username:  santhosh47
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
