# Site settings
title: Santhosh Kumar
description: My Modern Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://santhoshms47.github.io/

# User settings
username: Santhosh Kumar
user_description: I'm a Student, Programmer, Developer and Designer. My objective is to give my best to achieve a challenging task or goal with my academic knowledge and skills. Always open to learn the latest technologies.
user_title: Student | Programmer
email: santhoshkms47@gmail.com
twitter_username: santhosh47
github_username:  santhosh47
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
